# Generated by Django 5.1.2 on 2024-11-17 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
